language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"

before_install:
  - sudo apt-add-repository --yes ppa:mapnik/v2.2.0
  - sudo apt-get update
  - sudo apt-get install libprotobuf7 libprotobuf-dev protobuf-compiler libmapnik libmapnik-dev

before_script:
  - npm install mocha
