os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: 0.10.40
  MapboxAccessToken:
    secure: 01rO70zKIKzh2l8htHugNS3cCk9u3LfTu2SXojFaYkveumhZRDgRrH/BroS+fIv8T6YB5l0P2nvKAjqhdDW2yuaLWGIB5KdBmhywp4dXa0g=
  AWS_ACCESS_KEY_ID:
    secure: OBZOTIMd7fPLEMiTp6wqBPxDdh89++4el/PFz2PU7uo=
  AWS_SECRET_ACCESS_KEY:
    secure: 3J9cHNPVgtrqmUufBdyKPqqSeSq4H5IfvKlbuyHG4h5jfKsa24gBjSNBaeKeAXl5

platform:
  - x64
  - x86

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
